name: Auto merge
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:

  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: main
        run: deno run --allow-net --location https://example.com --no-check auto-merge/mod.ts ${{ github.repository }} ${{ github.token }} ${{ github.event.number }}
