name: Minify & Publish files
on:
  push:
    branches:
      - meta
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Minify and Publish files
        run: deno run --allow-read --allow-write --unstable --quiet repo/jobs/publish/mod.ts repo output
        working-directory: .
